<?php
/**
 * install/index.php — Web-based Installer (WordPress-style)
 * Steps: 1=Requirements  2=Database  3=Import SQL  4=Admin Account  5=Done
 *
 * After install completes:
 *  - config/config.php is written
 *  - install/ folder is renamed/blocked
 */

// Prevent running if already installed
if (file_exists(dirname(__DIR__) . '/config/config.php') &&
    file_exists(dirname(__DIR__) . '/install/.installed')) {
    header('Location: ../index.php');
    exit;
}

session_start();
define('INSTALLER', true);

$step    = (int) ($_GET['step'] ?? 1);
$errors  = [];
$success = '';

// ── Helper ──────────────────────────────────────────────────
function req_check(): array {
    return [
        ['PHP 8.1+',           version_compare(PHP_VERSION, '8.1.0', '>=')],
        ['PDO Extension',      extension_loaded('pdo')],
        ['PDO MySQL',          extension_loaded('pdo_mysql')],
        ['OpenSSL',            extension_loaded('openssl')],
        ['Fileinfo',           extension_loaded('fileinfo')],
        ['Mbstring',           extension_loaded('mbstring')],
        ['config/ writable',   is_writable(dirname(__DIR__) . '/config')],
        ['uploads/ writable',  is_writable(dirname(__DIR__) . '/uploads')],
    ];
}

function test_db(string $host, string $user, string $pass, string $db): bool|string {
    try {
        $pdo = new PDO(
            "mysql:host={$host};charset=utf8mb4",
            $user, $pass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$db}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        return true;
    } catch (PDOException $e) {
        return $e->getMessage();
    }
}

function run_sql(string $host, string $user, string $pass, string $db, string $sql_file): bool|string {
    try {
        $pdo = new PDO(
            "mysql:host={$host};dbname={$db};charset=utf8mb4",
            $user, $pass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        $sql = file_get_contents($sql_file);
        // Strip CREATE DATABASE / USE statements so we use our db
        $sql = preg_replace('/^(CREATE DATABASE|USE)\s+[^;]+;/im', '', $sql);
        $pdo->exec($sql);
        return true;
    } catch (PDOException $e) {
        return $e->getMessage();
    }
}

function write_config(string $host, string $user, string $pass, string $db, string $site_url): void {
    $tpl = <<<PHP
<?php
/**
 * School ERP - Configuration (auto-generated by installer)
 */
error_reporting(0);
ini_set('display_errors', 0);

ini_set('session.cookie_httponly', 1);
ini_set('session.use_strict_mode', 1);
ini_set('session.cookie_samesite', 'Lax');
if (session_status() === PHP_SESSION_NONE) session_start();

define('DB_HOST',    '{$host}');
define('DB_USER',    '{$user}');
define('DB_PASS',    '{$pass}');
define('DB_NAME',    '{$db}');
define('DB_CHARSET', 'utf8mb4');

define('SITE_URL',      rtrim('{$site_url}', '/'));
define('ROOT_PATH',     dirname(__DIR__) . '/');
define('CONFIG_PATH',   ROOT_PATH . 'config/');
define('INCLUDES_PATH', ROOT_PATH . 'includes/');
define('UPLOADS_PATH',  ROOT_PATH . 'uploads/');
define('ASSETS_URL',    SITE_URL . '/assets');
define('UPLOADS_URL',   SITE_URL . '/uploads');

define('CSRF_TOKEN_LENGTH', 32);
define('OTP_EXPIRY_MINUTES', 10);
define('SESSION_TIMEOUT',    1800);
define('APP_NAME',           'School ERP System');
define('APP_VERSION',        '1.0.0');
define('ACADEMIC_YEAR',      '2025-2026');
define('PASS_PERCENTAGE',     33);
define('MAX_FILE_SIZE',      5 * 1024 * 1024);
define('ALLOWED_IMAGES',     ['jpg','jpeg','png','gif','webp']);
define('ALLOWED_DOCS',       ['pdf','doc','docx','jpg','jpeg','png']);

date_default_timezone_set('Asia/Kolkata');

require_once CONFIG_PATH . 'database.php';
require_once INCLUDES_PATH . 'functions.php';
require_once INCLUDES_PATH . 'notifications.php';

function get_setting(string \$key, string \$default = ''): string {
    global \$pdo;
    static \$cache = [];
    if (!isset(\$cache[\$key])) {
        try {
            \$stmt = \$pdo->prepare("SELECT setting_value FROM settings WHERE setting_key=? LIMIT 1");
            \$stmt->execute([\$key]);
            \$row = \$stmt->fetch();
            \$cache[\$key] = \$row ? (string)\$row['setting_value'] : \$default;
        } catch (Exception \$e) { return \$default; }
    }
    return \$cache[\$key];
}
PHP;
    file_put_contents(dirname(__DIR__) . '/config/config.php', $tpl);
}

// ── Process steps ────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    if ($step === 2) {
        $_SESSION['inst_host']     = trim($_POST['db_host']    ?? 'localhost');
        $_SESSION['inst_user']     = trim($_POST['db_user']    ?? '');
        $_SESSION['inst_pass']     = $_POST['db_pass']         ?? '';
        $_SESSION['inst_db']       = trim($_POST['db_name']    ?? '');
        $_SESSION['inst_site_url'] = rtrim(trim($_POST['site_url'] ?? ''), '/');

        $result = test_db(
            $_SESSION['inst_host'],
            $_SESSION['inst_user'],
            $_SESSION['inst_pass'],
            $_SESSION['inst_db']
        );

        if ($result === true) {
            header('Location: ?step=3');
            exit;
        } else {
            $errors[] = 'Database connection failed: ' . $result;
        }
    }

    if ($step === 3) {
        $sql_file = dirname(__DIR__) . '/database.sql';
        if (!file_exists($sql_file)) {
            $errors[] = 'database.sql not found in project root.';
        } else {
            $result = run_sql(
                $_SESSION['inst_host'],
                $_SESSION['inst_user'],
                $_SESSION['inst_pass'],
                $_SESSION['inst_db'],
                $sql_file
            );
            if ($result === true) {
                header('Location: ?step=4');
                exit;
            } else {
                $errors[] = 'SQL import failed: ' . $result;
            }
        }
    }

    if ($step === 4) {
        $admin_name  = trim($_POST['admin_name']  ?? '');
        $admin_email = trim($_POST['admin_email'] ?? '');
        $admin_pass  = $_POST['admin_pass']       ?? '';
        $admin_pass2 = $_POST['admin_pass2']      ?? '';

        if (empty($admin_name))  $errors[] = 'Name required.';
        if (!filter_var($admin_email, FILTER_VALIDATE_EMAIL)) $errors[] = 'Invalid email.';
        if (strlen($admin_pass) < 8)  $errors[] = 'Password must be at least 8 characters.';
        if ($admin_pass !== $admin_pass2) $errors[] = 'Passwords do not match.';

        if (empty($errors)) {
            $pdo2 = new PDO(
                "mysql:host={$_SESSION['inst_host']};dbname={$_SESSION['inst_db']};charset=utf8mb4",
                $_SESSION['inst_user'], $_SESSION['inst_pass'],
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]
            );

            // Update or insert admin
            $hash = password_hash($admin_pass, PASSWORD_BCRYPT);
            $exists = $pdo2->prepare("SELECT id FROM users WHERE role='admin' LIMIT 1");
            $exists->execute();
            if ($exists->fetch()) {
                $pdo2->prepare("UPDATE users SET name=?,email=?,password=? WHERE role='admin' LIMIT 1")
                     ->execute([$admin_name, $admin_email, $hash]);
            } else {
                $pdo2->prepare("INSERT INTO users (name,email,password,role) VALUES (?,?,?,'admin')")
                     ->execute([$admin_name, $admin_email, $hash]);
            }

            // Update site_url in settings
            $site_url = $_SESSION['inst_site_url'];
            $pdo2->prepare("INSERT INTO settings (setting_key,setting_value) VALUES ('site_url',?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)")
                 ->execute([$site_url]);

            // Write config.php
            write_config(
                $_SESSION['inst_host'],
                $_SESSION['inst_user'],
                $_SESSION['inst_pass'],
                $_SESSION['inst_db'],
                $site_url
            );

            // Create .installed flag
            file_put_contents(__DIR__ . '/.installed', date('Y-m-d H:i:s'));

            header('Location: ?step=5');
            exit;
        }
    }
}

// ── Requirements check for step 1 ──────────────────────────
$reqs = req_check();
$all_pass = !in_array(false, array_column($reqs, 1));

$steps_meta = [
    1 => 'Requirements',
    2 => 'Database',
    3 => 'Import SQL',
    4 => 'Admin Account',
    5 => 'Complete',
];
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>School ERP — Installer</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
  <link href="../assets/css/style.css" rel="stylesheet">
  <style>
    body { min-height: 100vh; background: var(--navy); display: flex; align-items: center; justify-content: center; padding: 30px 16px; }
    body::before {
      content:'';
      position:fixed;inset:0;
      background-image:linear-gradient(rgba(245,166,35,0.025) 1px,transparent 1px),linear-gradient(90deg,rgba(245,166,35,0.025) 1px,transparent 1px);
      background-size:50px 50px;pointer-events:none;
    }
    .install-wrap { width: 100%; max-width: 600px; position: relative; z-index: 1; }
    .install-header {
      text-align: center;
      margin-bottom: 32px;
    }
    .install-logo {
      width: 72px; height: 72px;
      border-radius: 20px;
      background: linear-gradient(135deg, var(--gold), var(--gold-dark));
      display: flex; align-items: center; justify-content: center;
      font-size: 2rem;
      margin: 0 auto 16px;
      box-shadow: 0 8px 32px rgba(245,166,35,0.35);
    }
    .steps-bar {
      display: flex;
      align-items: center;
      gap: 0;
      margin-bottom: 32px;
    }
    .steps-bar .step-item {
      display: flex;
      flex-direction: column;
      align-items: center;
      flex: 1;
      position: relative;
    }
    .steps-bar .step-item::after {
      content: '';
      position: absolute;
      top: 18px;
      left: calc(50% + 18px);
      right: calc(-50% + 18px);
      height: 2px;
      background: var(--border);
    }
    .steps-bar .step-item:last-child::after { display: none; }
    .steps-bar .step-item.done::after { background: var(--gold); }
    .step-num {
      width: 36px; height: 36px;
      border-radius: 50%;
      border: 2px solid var(--border);
      background: rgba(255,255,255,0.04);
      color: var(--text-muted);
      display: flex; align-items: center; justify-content: center;
      font-size: 0.8rem; font-weight: 700;
      transition: all 0.3s;
      position: relative;
      z-index: 1;
    }
    .step-item.active .step-num { background: var(--gold); border-color: var(--gold); color: var(--navy); box-shadow: 0 0 0 4px rgba(245,166,35,0.2); }
    .step-item.done .step-num   { background: #22c55e; border-color: #22c55e; color: #fff; }
    .step-label { font-size: 0.65rem; color: var(--text-muted); margin-top: 6px; white-space: nowrap; }
    .step-item.active .step-label { color: var(--gold); }
    .step-item.done .step-label   { color: #4ade80; }
    .install-card {
      background: var(--navy-2);
      border: 1px solid var(--border);
      border-radius: 20px;
      padding: 32px;
      box-shadow: 0 24px 64px rgba(0,0,0,0.4);
    }
    .req-row {
      display: flex; align-items: center; justify-content: space-between;
      padding: 10px 14px;
      border-radius: 10px;
      background: rgba(255,255,255,0.03);
      border: 1px solid var(--border);
      margin-bottom: 8px;
      font-size: 0.875rem;
    }
    .req-row .name { color: var(--text-main); }
    .req-row .pass { color: #4ade80; }
    .req-row .fail { color: #f87171; }
  </style>
</head>
<body>
<div class="install-wrap">
  <!-- Header -->
  <div class="install-header">
    <div class="install-logo">🎓</div>
    <h2 style="font-family:'Playfair Display',serif;color:#fff;margin-bottom:4px;">School ERP Installer</h2>
    <p style="color:var(--text-muted);font-size:0.875rem;">Follow the steps to get your ERP running in minutes</p>
  </div>

  <!-- Steps bar -->
  <div class="steps-bar">
    <?php foreach ($steps_meta as $s => $label):
      $cls = $s < $step ? 'done' : ($s === $step ? 'active' : '');
    ?>
    <div class="step-item <?= $cls ?>">
      <div class="step-num">
        <?= $s < $step ? '<i class="bi bi-check"></i>' : $s ?>
      </div>
      <div class="step-label"><?= $label ?></div>
    </div>
    <?php endforeach; ?>
  </div>

  <!-- Card -->
  <div class="install-card">

    <?php if (!empty($errors)): ?>
    <div class="alert alert-danger mb-3">
      <ul class="mb-0">
        <?php foreach ($errors as $e): ?><li><?= htmlspecialchars($e) ?></li><?php endforeach; ?>
      </ul>
    </div>
    <?php endif; ?>

    <!-- ════ STEP 1: Requirements ════ -->
    <?php if ($step === 1): ?>
    <h4 style="font-family:'Playfair Display',serif;color:#fff;margin-bottom:20px;">
      <i class="bi bi-clipboard2-check text-gold me-2" style="color:var(--gold)"></i>Server Requirements
    </h4>

    <?php foreach ($reqs as [$name, $pass]): ?>
    <div class="req-row">
      <span class="name"><?= $name ?></span>
      <span class="<?= $pass ? 'pass' : 'fail' ?>">
        <i class="bi bi-<?= $pass ? 'check-circle-fill' : 'x-circle-fill' ?>"></i>
        <?= $pass ? 'OK' : 'FAILED' ?>
      </span>
    </div>
    <?php endforeach; ?>

    <?php if ($all_pass): ?>
    <a href="?step=2" class="btn btn-primary w-100 mt-4 btn-lg">
      <i class="bi bi-arrow-right me-2"></i>Continue to Database Setup
    </a>
    <?php else: ?>
    <div class="alert alert-danger mt-3">
      Please fix the failed requirements before continuing.
    </div>
    <?php endif; ?>

    <!-- ════ STEP 2: Database ════ -->
    <?php elseif ($step === 2): ?>
    <h4 style="font-family:'Playfair Display',serif;color:#fff;margin-bottom:20px;">
      <i class="bi bi-database me-2" style="color:var(--gold)"></i>Database Configuration
    </h4>
    <form method="POST">
      <div class="mb-3">
        <label class="form-label">Database Host</label>
        <input type="text" name="db_host" class="form-control"
               value="<?= htmlspecialchars($_SESSION['inst_host'] ?? 'localhost') ?>"
               placeholder="localhost" required>
        <div class="form-text">Usually <code>localhost</code> for cPanel.</div>
      </div>
      <div class="row g-3 mb-3">
        <div class="col-6">
          <label class="form-label">Database User</label>
          <input type="text" name="db_user" class="form-control"
                 value="<?= htmlspecialchars($_SESSION['inst_user'] ?? '') ?>"
                 placeholder="cpanel_dbuser" required>
        </div>
        <div class="col-6">
          <label class="form-label">Database Password</label>
          <input type="password" name="db_pass" class="form-control"
                 placeholder="••••••••">
        </div>
      </div>
      <div class="mb-3">
        <label class="form-label">Database Name</label>
        <input type="text" name="db_name" class="form-control"
               value="<?= htmlspecialchars($_SESSION['inst_db'] ?? '') ?>"
               placeholder="cpanel_schoolerp" required>
        <div class="form-text">The database will be created if it doesn't exist.</div>
      </div>
      <div class="mb-4">
        <label class="form-label">Site URL</label>
        <input type="url" name="site_url" class="form-control"
               value="<?= htmlspecialchars($_SESSION['inst_site_url'] ?? (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost')) ?>"
               placeholder="https://yourdomain.com" required>
        <div class="form-text">No trailing slash. Use HTTPS if available.</div>
      </div>
      <button type="submit" class="btn btn-primary w-100 btn-lg">
        <i class="bi bi-check-circle me-2"></i>Test & Save Connection
      </button>
    </form>

    <!-- ════ STEP 3: Import SQL ════ -->
    <?php elseif ($step === 3): ?>
    <h4 style="font-family:'Playfair Display',serif;color:#fff;margin-bottom:20px;">
      <i class="bi bi-cloud-upload me-2" style="color:var(--gold)"></i>Import Database
    </h4>
    <p style="color:var(--text-muted);font-size:0.9rem;margin-bottom:24px;">
      This will import all 18 tables, default classes, subjects, and settings from
      <code>database.sql</code> into your database.
      <br><br>
      <strong style="color:var(--gold);">⚠ This will overwrite any existing data in the database.</strong>
    </p>
    <div class="req-row mb-3">
      <span class="name">database.sql</span>
      <span class="<?= file_exists(dirname(__DIR__).'/database.sql') ? 'pass' : 'fail' ?>">
        <i class="bi bi-<?= file_exists(dirname(__DIR__).'/database.sql') ? 'check-circle-fill' : 'x-circle-fill' ?>"></i>
        <?= file_exists(dirname(__DIR__).'/database.sql') ? 'Found' : 'NOT FOUND' ?>
      </span>
    </div>
    <?php if (!file_exists(dirname(__DIR__).'/database.sql')): ?>
    <div class="alert alert-danger">
      Please upload <code>database.sql</code> to the project root folder first.
    </div>
    <?php else: ?>
    <form method="POST">
      <button type="submit" class="btn btn-primary w-100 btn-lg">
        <i class="bi bi-database-fill-up me-2"></i>Import database.sql Now
      </button>
    </form>
    <?php endif; ?>

    <!-- ════ STEP 4: Admin Account ════ -->
    <?php elseif ($step === 4): ?>
    <h4 style="font-family:'Playfair Display',serif;color:#fff;margin-bottom:20px;">
      <i class="bi bi-person-fill-lock me-2" style="color:var(--gold)"></i>Create Admin Account
    </h4>
    <form method="POST">
      <div class="mb-3">
        <label class="form-label">Admin Full Name</label>
        <input type="text" name="admin_name" class="form-control"
               value="<?= htmlspecialchars($_POST['admin_name'] ?? 'Super Admin') ?>"
               placeholder="Your full name" required>
      </div>
      <div class="mb-3">
        <label class="form-label">Admin Email</label>
        <input type="email" name="admin_email" class="form-control"
               value="<?= htmlspecialchars($_POST['admin_email'] ?? '') ?>"
               placeholder="admin@school.com" required>
      </div>
      <div class="row g-3 mb-4">
        <div class="col-6">
          <label class="form-label">Password</label>
          <input type="password" name="admin_pass" class="form-control"
                 placeholder="Min 8 characters" required minlength="8">
        </div>
        <div class="col-6">
          <label class="form-label">Confirm Password</label>
          <input type="password" name="admin_pass2" class="form-control"
                 placeholder="Repeat password" required>
        </div>
      </div>
      <button type="submit" class="btn btn-primary w-100 btn-lg">
        <i class="bi bi-person-check me-2"></i>Create Account & Finish
      </button>
    </form>

    <!-- ════ STEP 5: Done ════ -->
    <?php elseif ($step === 5): ?>
    <div class="text-center py-2">
      <div style="font-size:4rem;margin-bottom:16px;">🎉</div>
      <h3 style="font-family:'Playfair Display',serif;color:#fff;margin-bottom:8px;">
        Installation Complete!
      </h3>
      <p style="color:var(--text-muted);margin-bottom:28px;">
        Your School ERP is ready. Please delete or secure the
        <code>/install</code> folder to prevent re-running.
      </p>

      <div style="background:rgba(34,197,94,0.1);border:1px solid rgba(34,197,94,0.25);border-radius:12px;padding:16px;margin-bottom:24px;text-align:left;font-size:0.85rem;color:#4ade80;">
        <i class="bi bi-shield-check me-2"></i>
        <strong>Security reminder:</strong> Delete or rename the <code>/install</code> folder from your server now.
      </div>

      <div style="background:rgba(255,255,255,0.04);border:1px solid var(--border);border-radius:12px;padding:16px;margin-bottom:28px;text-align:left;">
        <div style="font-size:0.8rem;color:var(--text-muted);margin-bottom:8px;text-transform:uppercase;letter-spacing:0.08em;">Login Credentials</div>
        <div style="color:var(--text-main);font-size:0.875rem;">
          <strong>Admin URL:</strong> <code><?= htmlspecialchars($_SESSION['inst_site_url'] ?? '') ?>/admin/login.php</code><br>
          <strong>Student/Teacher URL:</strong> <code><?= htmlspecialchars($_SESSION['inst_site_url'] ?? '') ?>/auth/login.php</code>
        </div>
      </div>

      <div class="d-flex gap-3 justify-content-center">
        <a href="<?= htmlspecialchars(($_SESSION['inst_site_url'] ?? '..') . '/admin/login.php') ?>"
           class="btn btn-primary btn-lg">
          <i class="bi bi-shield-lock me-2"></i>Go to Admin Login
        </a>
        <a href="<?= htmlspecialchars($_SESSION['inst_site_url'] ?? '..') ?>"
           class="btn btn-secondary btn-lg">
          <i class="bi bi-house me-2"></i>Visit Website
        </a>
      </div>
    </div>
    <?php endif; ?>

  </div><!-- /.install-card -->
</div><!-- /.install-wrap -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
